name: CI

on:
  pull_request:
    branches: [develop, main]
  push:
    branches: [develop]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Update npm
        run: npm install -g npm@latest

      - name: Debug - Check files
        run: |
          echo "=== Current directory ==="
          pwd
          echo "=== Files in root ==="
          ls -la
          echo "=== Check package-lock.json ==="
          if [ -f "package-lock.json" ]; then
            echo "package-lock.json exists"
            head -5 package-lock.json
          else
            echo "package-lock.json NOT FOUND"
          fi

      - name: Install dependencies
        run: npm install

      - name: Install Prisma dependencies
        run: |
          cd apps/web
          npm install prisma @prisma/client

      - name: Generate Prisma Client
        run: |
          cd apps/web
          npx prisma generate

      - name: Run linter
        run: npm run lint || true
        
      - name: Run type check
        run: npm run type-check || true
        
      - name: Run tests
        run: npm test --if-present
        
      - name: Build project
        run: npm run build
